//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod collection;
pub mod config;
pub mod favorite;
pub mod page;
pub mod submission;
pub mod video;
pub mod watch_later;
pub mod youtube_channel;
pub mod youtube_video;
