//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::favorite::Entity as Favorite;
pub use super::page::Entity as Page;
pub use super::video::Entity as Video;
pub use super::video_source::Entity as VideoSource;
