//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use either::Either;
use sea_orm::entity::prelude::*;

use crate::string_vec::StringVec;
use crate::upper_vec::{Upper, UpperVec};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[sea_orm(table_name = "video")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub collection_id: Option<i32>,
    pub favorite_id: Option<i32>,
    pub watch_later_id: Option<i32>,
    pub submission_id: Option<i32>,
    pub upper_id: i64,
    pub upper_name: String,
    pub upper_face: String,
    pub staff: Option<UpperVec>,
    pub name: String,
    pub path: String,
    pub category: i32,
    pub bvid: String,
    pub intro: String,
    pub cover: String,
    pub ctime: DateTime,
    pub pubtime: DateTime,
    pub favtime: DateTime,
    pub download_status: u32,
    pub valid: bool,
    pub should_download: bool,
    pub tags: Option<StringVec>,
    pub single_page: Option<bool>,
    pub created_at: String,
}

impl Model {
    pub fn uppers(&self) -> Either<impl Iterator<Item = Upper<i64, &str>>, impl Iterator<Item = Upper<i64, &str>>> {
        if let Some(staff) = self.staff.as_ref() {
            Either::Left(staff.0.iter().map(|u| u.as_ref()))
        } else {
            Either::Right(std::iter::once(Upper::<i64, &str> {
                mid: self.upper_id,
                name: self.upper_name.as_str(),
                face: self.upper_face.as_str(),
                title: None,
            }))
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::page::Entity")]
    Page,
}

impl Related<super::page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Page.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
