//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "video")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub favorite_id: i32,
    pub upper_id: i32,
    pub name: String,
    pub path: String,
    pub category: String,
    pub bvid: String,
    pub intro: String,
    pub cover: String,
    pub ctime: String,
    pub pubtime: String,
    pub favtime: String,
    pub downloaded: bool,
    pub valid: bool,
    pub tags: String,
    pub single_page: bool,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
