name: Docker Image CI (DEBUG)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            - 
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ secrets.DOCKERHUB_USERNAME }}/bili-sync
                    tags: |
                        type=raw,value=debug
            - 
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v3
            - 
                name: Set Up Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            - 
                name: Build and push images
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: Dockerfile
                    platforms: |
                        linux/amd64
                        linux/arm64/v8
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=gha, scope=${{ github.workflow }}
                    cache-to: type=gha, scope=${{ github.workflow }}          